catalog:
  '@babylonjs/core': ^8.0.0
  '@biomejs/biome': 2.2.4
  '@tailwindcss/vite': ^4.0.0
  '@tsconfig/node24': ^24.0.0
  '@tsconfig/strictest': ^2.0.6
  '@tsconfig/vite-react': ^7.0.0
  '@types/node': ^24.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@vitejs/plugin-react': ^5.0.0
  react: ^19.0.0
  react-dom: ^19.0.0
  tailwindcss: ^4.0.0
  typescript: ~5.9.0
  vite: ^7.0.0
  vitest: ^3.0.0

workspaces:
  - packages/*
  - plugins-editor/*
  - plugins-runtime/*
